python3 run.py\
        --task_id 5\
        --exp_name "without_force_goal_only"\
        --gui \
        --stage train\
        --batch_size 64\
        --action_penalty 0.2\
        --start_learning_episode 1000\
        --comment "action_penalty_0.2_critic_goal_only"
